// Auto-generated by `python -m groundextract.export` - do not edit.
window.__GROUNDEXTRACT_FIXTURES__ = {
  "clean": {
    "doc_text": "\uc804\uc790\uc138\uae08\uacc4\uc0b0\uc11c\n\uc791\uc131\uc77c\uc790 2026-07-01  \uc2b9\uc778\ubc88\ud638 20260701-41000000-12345678\n\uacf5\uae09\uc790 \uc8fc\uc2dd\ud68c\uc0ac \uac00\uc628\uc18c\ud504\ud2b8  \uacf5\uae09\ubc1b\ub294\uc790 \uc8fc\uc2dd\ud68c\uc0ac \ub098\ub798\uc0c1\uc0ac\n\n\ud488\ubaa91 \uacf5\uae09\uac00  400,000\uc6d0\n\ud488\ubaa92 \uacf5\uae09\uac00  600,000\uc6d0\n\n\uacf5\uae09\uac00\uc561  1,000,000\uc6d0\n\uc138\uc561        100,000\uc6d0\n\ud569\uacc4\uae08\uc561  1,100,000\uc6d0\n",
    "summary": {
      "total": 5,
      "verified": 5,
      "discarded": 0,
      "ungrounded": 0
    },
    "fields": [
      {
        "field": "item1_supply",
        "value": {
          "field": "item1_supply",
          "raw": "400,000\uc6d0",
          "number": 400000,
          "grounding_quote": "\ud488\ubaa91 \uacf5\uae09\uac00  400,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '400,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "supply_equals_sum_of_items",
            "passed": true,
            "detail": "supply=1e+06 vs sum(item1_supply+item2_supply)=1e+06",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      },
      {
        "field": "item2_supply",
        "value": {
          "field": "item2_supply",
          "raw": "600,000\uc6d0",
          "number": 600000,
          "grounding_quote": "\ud488\ubaa92 \uacf5\uae09\uac00  600,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '600,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "supply_equals_sum_of_items",
            "passed": true,
            "detail": "supply=1e+06 vs sum(item1_supply+item2_supply)=1e+06",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      },
      {
        "field": "supply",
        "value": {
          "field": "supply",
          "raw": "1,000,000\uc6d0",
          "number": 1000000,
          "grounding_quote": "\uacf5\uae09\uac00\uc561  1,000,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '1,000,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "vat_equals_supply_x_10pct",
            "passed": true,
            "detail": "100000 vs 100000 (tol 1) -> diff 0",
            "kind": null
          },
          {
            "name": "total_equals_supply_plus_vat",
            "passed": true,
            "detail": "1.1e+06 vs 1.1e+06 (tol 1) -> diff 0",
            "kind": null
          },
          {
            "name": "supply_equals_sum_of_items",
            "passed": true,
            "detail": "supply=1e+06 vs sum(item1_supply+item2_supply)=1e+06",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      },
      {
        "field": "vat",
        "value": {
          "field": "vat",
          "raw": "100,000\uc6d0",
          "number": 100000,
          "grounding_quote": "\uc138\uc561        100,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '100,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "vat_equals_supply_x_10pct",
            "passed": true,
            "detail": "100000 vs 100000 (tol 1) -> diff 0",
            "kind": null
          },
          {
            "name": "total_equals_supply_plus_vat",
            "passed": true,
            "detail": "1.1e+06 vs 1.1e+06 (tol 1) -> diff 0",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      },
      {
        "field": "total",
        "value": {
          "field": "total",
          "raw": "1,100,000\uc6d0",
          "number": 1100000,
          "grounding_quote": "\ud569\uacc4\uae08\uc561  1,100,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '1,100,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "total_equals_supply_plus_vat",
            "passed": true,
            "detail": "1.1e+06 vs 1.1e+06 (tol 1) -> diff 0",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      }
    ]
  },
  "injected": {
    "doc_text": "\uc804\uc790\uc138\uae08\uacc4\uc0b0\uc11c\n\uc791\uc131\uc77c\uc790 2026-07-01  \uc2b9\uc778\ubc88\ud638 20260701-41000000-12345678\n\uacf5\uae09\uc790 \uc8fc\uc2dd\ud68c\uc0ac \uac00\uc628\uc18c\ud504\ud2b8  \uacf5\uae09\ubc1b\ub294\uc790 \uc8fc\uc2dd\ud68c\uc0ac \ub098\ub798\uc0c1\uc0ac\n\n\ud488\ubaa91 \uacf5\uae09\uac00  400,000\uc6d0\n\ud488\ubaa92 \uacf5\uae09\uac00  600,000\uc6d0\n\n\uacf5\uae09\uac00\uc561  1,000,000\uc6d0\n\uc138\uc561        100,000\uc6d0\n\ud569\uacc4\uae08\uc561  1,100,000\uc6d0\n",
    "summary": {
      "total": 5,
      "verified": 2,
      "discarded": 3,
      "ungrounded": 1
    },
    "fields": [
      {
        "field": "item1_supply",
        "value": {
          "field": "item1_supply",
          "raw": "400,000\uc6d0",
          "number": 400000,
          "grounding_quote": "\ud488\ubaa91 \uacf5\uae09\uac00  400,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '400,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "supply_equals_sum_of_items",
            "passed": true,
            "detail": "supply=1e+06 vs sum(item1_supply+item2_supply)=1e+06",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      },
      {
        "field": "item2_supply",
        "value": {
          "field": "item2_supply",
          "raw": "600,000\uc6d0",
          "number": 600000,
          "grounding_quote": "\ud488\ubaa92 \uacf5\uae09\uac00  600,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '600,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "supply_equals_sum_of_items",
            "passed": true,
            "detail": "supply=1e+06 vs sum(item1_supply+item2_supply)=1e+06",
            "kind": null
          }
        ],
        "verdict": "verified",
        "confidence": 1.0
      },
      {
        "field": "supply",
        "value": {
          "field": "supply",
          "raw": "1,000,000\uc6d0",
          "number": 1000000,
          "grounding_quote": "\uacf5\uae09\uac00\uc561  1,000,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '1,000,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "vat_equals_supply_x_10pct",
            "passed": false,
            "detail": "250000 vs 100000 (tol 1) -> diff 150000",
            "kind": null
          },
          {
            "name": "total_equals_supply_plus_vat",
            "passed": false,
            "detail": "1.1e+06 vs 1.25e+06 (tol 1) -> diff 150000",
            "kind": null
          },
          {
            "name": "supply_equals_sum_of_items",
            "passed": true,
            "detail": "supply=1e+06 vs sum(item1_supply+item2_supply)=1e+06",
            "kind": null
          }
        ],
        "verdict": "discarded",
        "confidence": 0.0
      },
      {
        "field": "vat",
        "value": {
          "field": "vat",
          "raw": "250,000\uc6d0",
          "number": 250000,
          "grounding_quote": "\uc138\uc561        100,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": false,
            "detail": "no grounding (best fuzzy ratio=0.56)",
            "kind": "none"
          },
          {
            "name": "vat_equals_supply_x_10pct",
            "passed": false,
            "detail": "250000 vs 100000 (tol 1) -> diff 150000",
            "kind": null
          },
          {
            "name": "total_equals_supply_plus_vat",
            "passed": false,
            "detail": "1.1e+06 vs 1.25e+06 (tol 1) -> diff 150000",
            "kind": null
          }
        ],
        "verdict": "discarded",
        "confidence": 0.0
      },
      {
        "field": "total",
        "value": {
          "field": "total",
          "raw": "1,100,000\uc6d0",
          "number": 1100000,
          "grounding_quote": "\ud569\uacc4\uae08\uc561  1,100,000\uc6d0",
          "page": null,
          "bbox": null,
          "confidence": 1.0
        },
        "checks": [
          {
            "name": "grounding",
            "passed": true,
            "detail": "verbatim substring: '1,100,000\uc6d0'",
            "kind": "exact"
          },
          {
            "name": "total_equals_supply_plus_vat",
            "passed": false,
            "detail": "1.1e+06 vs 1.25e+06 (tol 1) -> diff 150000",
            "kind": null
          }
        ],
        "verdict": "discarded",
        "confidence": 0.0
      }
    ]
  }
};
