"""Viewer fixture exporter: run the real gate, dump JSON for the static demo.

``python -m groundextract.export`` writes fixtures under ``viewer/fixtures/``:

  * ``clean.json``    - a normal tax invoice: every field grounds verbatim and
    every arithmetic invariant holds, so all fields come out VERIFIED.
  * ``injected.json`` - the same document with a hallucinated VAT injected into
    the extraction: the model cites the *real* VAT line but claims 250,000원, a
    number that appears nowhere in the document. Grounding fails AND the
    vat/total invariants break, so ``vat`` is DISCARDED and the violated rules
    taint their sibling fields ``supply``/``total`` (intended over-discard,
    measured as precision loss in the bench).
  * ``fixtures.js``   - both fixtures as ``window.__GROUNDEXTRACT_FIXTURES__``
    so ``viewer/index.html`` also works over ``file://`` where ``fetch()`` of
    local JSON is blocked by the browser.

Both JSON files share the schema the viewer reads:

    {"doc_text": str, "summary": {...}, "fields": [VerifiedField.to_dict()]}

Fixtures are produced by actually running ``run_gate`` over the rule pack
(never hand-written), so the viewer always shows real gate behaviour.
"""

from __future__ import annotations

import json
from pathlib import Path

from .gate import run_gate, summarize
from .models import ExtractedValue
from .rules import default_rules_dir, load_rule_pack

_ROOT = Path(__file__).resolve().parent.parent
_RULES = default_rules_dir() / "tax_invoice.yaml"
_FIXTURES_DIR = _ROOT / "viewer" / "fixtures"

# The ``__main__`` demo invoice, extended with line items so the sum invariant
# participates and sibling contamination is visible in the viewer.
_DOC = (
    "전자세금계산서\n"
    "작성일자 2026-07-01  승인번호 20260701-41000000-12345678\n"
    "공급자 주식회사 가온소프트  공급받는자 주식회사 나래상사\n"
    "\n"
    "품목1 공급가  400,000원\n"
    "품목2 공급가  600,000원\n"
    "\n"
    "공급가액  1,000,000원\n"
    "세액        100,000원\n"
    "합계금액  1,100,000원\n"
)


def _clean_values() -> list[ExtractedValue]:
    """A faithful extraction: every value grounds and all invariants hold."""
    return [
        ExtractedValue("item1_supply", "400,000원", 400_000, "품목1 공급가  400,000원"),
        ExtractedValue("item2_supply", "600,000원", 600_000, "품목2 공급가  600,000원"),
        ExtractedValue("supply", "1,000,000원", 1_000_000, "공급가액  1,000,000원"),
        ExtractedValue("vat", "100,000원", 100_000, "세액        100,000원"),
        ExtractedValue("total", "1,100,000원", 1_100_000, "합계금액  1,100,000원"),
    ]


def _injected_values() -> list[ExtractedValue]:
    """Clean extraction with a hallucinated VAT swapped in.

    The cited quote is the *real* VAT line (so the viewer can locate and
    highlight the span), but the claimed value 250,000원 exists nowhere in the
    document: grounding fails, and vat/total arithmetic invariants break.
    """
    hallucinated = ExtractedValue("vat", "250,000원", 250_000, "세액        100,000원")
    return [hallucinated if v.field == "vat" else v for v in _clean_values()]


def build_fixture(values: list[ExtractedValue], doc_text: str = _DOC) -> dict:
    """Run the real gate over ``values`` and shape the viewer payload."""
    pack = load_rule_pack(_RULES)
    fields = run_gate(values, doc_text, pack)
    return {
        "doc_text": doc_text,
        "summary": summarize(fields, pack),
        "fields": [f.to_dict() for f in fields],
    }


def export_fixtures(out_dir: str | Path = _FIXTURES_DIR) -> dict[str, Path]:
    """Write clean/injected fixtures (+ ``file://`` fallback JS); return paths."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    fixtures = {
        "clean": build_fixture(_clean_values()),
        "injected": build_fixture(_injected_values()),
    }

    paths: dict[str, Path] = {}
    for name, fixture in fixtures.items():
        path = out / f"{name}.json"
        path.write_text(
            json.dumps(fixture, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        paths[name] = path

    # file:// fallback: loading via <script src="fixtures/fixtures.js"> works
    # where fetch() of local files is blocked. ensure_ascii keeps the payload
    # encoding-proof regardless of how the browser sniffs the .js charset.
    js_path = out / "fixtures.js"
    js_path.write_text(
        "// Auto-generated by `python -m groundextract.export` - do not edit.\n"
        "window.__GROUNDEXTRACT_FIXTURES__ = "
        + json.dumps(fixtures, ensure_ascii=True, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    paths["fixtures_js"] = js_path
    return paths


def main() -> None:
    for name, path in export_fixtures().items():
        print(f"wrote {name:11} -> {path}")


if __name__ == "__main__":
    main()
